import { GetServerSidePropsContext } from 'next'
import { ParsedUrlQuery } from 'querystring'
import Head from 'next/head'

import { Result } from '../lib/types'
import db from '../lib/db'
import ResultsList from '../components/ResultsList'
import SearchForm from '../components/SearchForm'

import styles from '../styles/Home.module.css'

interface HomeProps {
  platform: string | null
  id: string | null
  results: Result[]
}

const getResults = async (platform: string | null, id: string | null) => {
  if (!platform || !id) return []
  try {
    const results = await db.query(
      `
        SELECT
          platform_tag AS platform,
          tag          AS id,
          description  AS desc
        FROM public.get_links($1, $2);
      `,
      [platform, id]
    )
    return results.rows
  } catch (error) {
    console.error(error)
    return []
  }
}

const processQuery = (query: ParsedUrlQuery) => {
  let platform = query.platform || null
  let id = query.id || null
  if (Array.isArray(platform)) {
    platform = platform.join()
  }
  if (Array.isArray(id)) {
    id = id.join()
  }
  return { platform, id }
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const { query } = context
  const { platform, id } = processQuery(query)
  const results = await getResults(platform, id)
  return {
    props: { platform, id, results },
  }
}

export default function Home(props: HomeProps) {
  const { platform, id, results } = props
  let title = 'Also'
  if (platform && id) {
    title += `: ${props.platform}/${props.id}`
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <h1 className={styles.title}>also</h1>
      </header>

      <main className={styles.main}>
        <SearchForm platform={platform} id={id} />
        <ResultsList results={results} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/dGrowl"
          target="_blank"
          rel="noopener noreferrer"
        >
          dGrowl@GitHub
        </a>
      </footer>
    </div>
  )
}
