import { GetServerSidePropsContext } from 'next'
import Head from 'next/head'

import { Result } from '../lib/types'

import SearchForm from '../components/SearchForm'
import ResultsList from '../components/ResultsList'

import styles from '../styles/Home.module.css'

interface HomeProps {
  platform: string | null
  id: string | null
  results: Result[]
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const { query } = context
  const platform = query.platform || null
  const id = query.id || null
  const results = id && platform ? [{ platform, id }] : []
  return {
    props: { platform, id, results },
  }
}

export default function Home(props: HomeProps) {
  let title = 'Also'
  const { platform, id, results } = props
  if (platform && id) {
    title += `: ${props.platform}/${props.id}`
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <h1 className={styles.title}>also</h1>
      </header>

      <main className={styles.main}>
        <SearchForm platform={platform} id={id} />
        <ResultsList results={results} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/dGrowl"
          target="_blank"
          rel="noopener noreferrer"
        >
          dGrowl@GitHub
        </a>
      </footer>
    </div>
  )
}
