import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Also (Known As)</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          also
        </h1>

        <form className={styles.form}>
          <label>Platform</label>
          <select name="platform">
            <option>Any</option>
            <option>Twitch</option>
            <option>Twitter</option>
          </select>
          <label>ID</label>
          <input name="id" defaultValue="aplusk" />
          <input type="submit" value="Search" />
        </form>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/dGrowl"
          target="_blank"
          rel="noopener noreferrer"
        >
          dGrowl@GitHub
        </a>
      </footer>
    </div>
  )
}
